-- EN LA SEMANA 2 CREACION DE USUARIO ASIGNANDOLE ROLES Y PRIVILEGIOS DESDE LINEAS DE CODIGO SQL
show user;
alter session set "_ORACLE_SCRIPT" = true; 

-- UNA VEZ ALTERADO LA SESION PROCEDEREMOS A CREAR NUESTRO USUARIO
-- USER SQL
CREATE USER EF_ESTADISTICA IDENTIFIED BY hola -- jesus alberto soria llantoy
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- A NUESTRO USUARIO YA CREADO LE OTORGAREMOS ROLES Y PRIVILEGIOS
-- ROLES
GRANT "CONNECT" TO EF_ESTADISTICA;
GRANT "RESOURCE" TO EF_ESTADISTICA;
ALTER USER EF_ESTADISTICA DEFAULT ROLE "CONNECT","RESOURCE";
-- SYSTEM PRIVILEGES
GRANT UNLIMITED TABLESPACE TO EF_ESTADISTICA;

-------------------------------------------------------------------------------------------------------------

-- UNA VEZ ALTERADO LA SESION PROCEDEREMOS A CREAR NUESTRO USUARIO
-- USER SQL
CREATE USER EF_PLAN_ESTUDIO IDENTIFIED BY hola -- jesus alberto soria llantoy
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- A NUESTRO USUARIO YA CREADO LE OTORGAREMOS ROLES Y PRIVILEGIOS
-- ROLES
GRANT "CONNECT" TO EF_PLAN_ESTUDIO;
GRANT "RESOURCE" TO EF_PLAN_ESTUDIO;
ALTER USER EF_PLAN_ESTUDIO DEFAULT ROLE "CONNECT","RESOURCE";
-- SYSTEM PRIVILEGES
GRANT UNLIMITED TABLESPACE TO EF_PLAN_ESTUDIO;


-------------------------------------------------------------------------------------------------------------

-- UNA VEZ ALTERADO LA SESION PROCEDEREMOS A CREAR NUESTRO USUARIO
-- USER SQL
CREATE USER EXAMEN_FINAL IDENTIFIED BY hola -- jesus alberto soria llantoy
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- A NUESTRO USUARIO YA CREADO LE OTORGAREMOS ROLES Y PRIVILEGIOS
-- ROLES
GRANT "CONNECT" TO EXAMEN_FINAL;
GRANT "RESOURCE" TO EXAMEN_FINAL;
ALTER USER EXAMEN_FINAL DEFAULT ROLE "CONNECT","RESOURCE";
-- SYSTEM PRIVILEGES
GRANT UNLIMITED TABLESPACE TO EXAMEN_FINAL;

-------------------------------------------------------------------------------------------------------------

-- UNA VEZ ALTERADO LA SESION PROCEDEREMOS A CREAR NUESTRO USUARIO
-- USER SQL
CREATE USER CASO_TOROS IDENTIFIED BY hola -- jesus alberto soria llantoy
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- A NUESTRO USUARIO YA CREADO LE OTORGAREMOS ROLES Y PRIVILEGIOS
-- ROLES
GRANT "CONNECT" TO CASO_TOROS;
GRANT "RESOURCE" TO CASO_TOROS;
ALTER USER CASO_TOROS DEFAULT ROLE "CONNECT","RESOURCE";
-- SYSTEM PRIVILEGES
GRANT UNLIMITED TABLESPACE TO CASO_TOROS;


-------------------------------------------------------------------------------------------------------------

-- UNA VEZ ALTERADO LA SESION PROCEDEREMOS A CREAR NUESTRO USUARIO
-- USER SQL
CREATE USER GODLUNCH_18062023 IDENTIFIED BY hola -- jesus alberto soria llantoy
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- A NUESTRO USUARIO YA CREADO LE OTORGAREMOS ROLES Y PRIVILEGIOS
-- ROLES
GRANT "CONNECT" TO GODLUNCH_18062023;
GRANT "RESOURCE" TO GODLUNCH_18062023;
ALTER USER GODLUNCH_18062023 DEFAULT ROLE "CONNECT","RESOURCE";
-- SYSTEM PRIVILEGES
GRANT UNLIMITED TABLESPACE TO GODLUNCH_18062023;


-------------------------------------------------------------------------------------------------------------

-- UNA VEZ ALTERADO LA SESION PROCEDEREMOS A CREAR NUESTRO USUARIO
-- USER SQL
CREATE USER SANLUIS IDENTIFIED BY SANLUIS -- jesus alberto soria llantoy
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- A NUESTRO USUARIO YA CREADO LE OTORGAREMOS ROLES Y PRIVILEGIOS
-- ROLES
GRANT "CONNECT" TO SANLUIS;
GRANT "RESOURCE" TO SANLUIS;
ALTER USER SANLUIS DEFAULT ROLE "CONNECT","RESOURCE";
-- SYSTEM PRIVILEGES
GRANT UNLIMITED TABLESPACE TO SANLUIS;
