-- EN LA SEMANA 2 CREACION DE USUARIO ASIGNANDOLE ROLES Y PRIVILEGIOS DESDE LINEAS DE CODIGO SQL
show user;
alter session set "_ORACLE_SCRIPT" = true; 

-- UNA VEZ ALTERADO LA SESION PROCEDEREMOS A CREAR NUESTRO USUARIO
-- USER SQL
CREATE USER EF_ESTADISTICA IDENTIFIED BY hola -- jesus alberto soria llantoy
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- A NUESTRO USUARIO YA CREADO LE OTORGAREMOS ROLES Y PRIVILEGIOS
-- ROLES
GRANT "CONNECT" TO EF_ESTADISTICA;
GRANT "RESOURCE" TO EF_ESTADISTICA;
ALTER USER EF_ESTADISTICA DEFAULT ROLE "CONNECT","RESOURCE";
-- SYSTEM PRIVILEGES
GRANT UNLIMITED TABLESPACE TO EF_ESTADISTICA;

-------------------------------------------------------------------------------------------------------------

-- UNA VEZ ALTERADO LA SESION PROCEDEREMOS A CREAR NUESTRO USUARIO
-- USER SQL
CREATE USER EF_PLAN_ESTUDIO IDENTIFIED BY hola -- jesus alberto soria llantoy
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- A NUESTRO USUARIO YA CREADO LE OTORGAREMOS ROLES Y PRIVILEGIOS
-- ROLES
GRANT "CONNECT" TO EF_PLAN_ESTUDIO;
GRANT "RESOURCE" TO EF_PLAN_ESTUDIO;
ALTER USER EF_PLAN_ESTUDIO DEFAULT ROLE "CONNECT","RESOURCE";
-- SYSTEM PRIVILEGES
GRANT UNLIMITED TABLESPACE TO EF_PLAN_ESTUDIO;

